+ Added new release actions, every time we merge into main it will   create a release by extracting the version fromwinutil.ps1 and setting   all appropriate tags and versions

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,24 +1,56 @@
-name: Update Branch
+name: Release WinUtil
 
 on:
   push: 
     branches: 
       - main
-      - test*
-
+      
 jobs:
   build-runspace:
     runs-on: windows-latest
     steps:
-    - uses: actions/checkout@v4
-      with:
-        ref: ${{ github.head_ref }}
-    - name: Compile project
-      shell: pwsh
-      run: |
-        Set-ExecutionPolicy Bypass -Scope Process -Force; ./Compile.ps1
-      continue-on-error: false # Directly fail the job on error, removing the need for a separate check
-    - uses: stefanzweifel/git-auto-commit-action@v5
-      with:
-        commit_message: Compile Winutil
-      if: success()
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      - name: Run compile.ps1
+        run: Set-ExecutionPolicy Bypass -Scope Process -Force; ./Compile.ps1
+        shell: pwsh
+        
+      - name: Extract Version from winutil.ps1
+        id: extract_version
+        run: |
+          $version = ''
+          Get-Content ./winutil.ps1 -TotalCount 30 | ForEach-Object {
+            if ($_ -match 'Version\s*:\s*(\d{2}\.\d{2}\.\d{2})') {
+              $version = $matches[1]
+              echo "##[set-output name=version;]$version"
+              break
+            }
+          }
+          if (-not $version) {
+            Write-Error "Version not found in winutil.ps1"
+            exit 1
+          }
+        shell: pwsh       
+
+      - name: Create Release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ steps.extract_version.outputs.version }}
+          release_name: Release ${{ steps.extract_version.outputs.version }}
+          body: Release Notes
+          draft: false
+          prerelease: false
+
+      - name: Upload Release Asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ./winutil.ps1
+          asset_name: winutil.ps1
+          asset_content_type: text/plain
